@extends('layouts.app')

@section('content')
<div class="container py-5">
    <div class="row justify-content-center">
        <div class="col-md-10 col-lg-8">
            <h1 class="mb-4">Privacy Policy</h1>
            <p class="text-muted">Last updated: May 6, 2025</p>

            <p>This service is operated in the United States. By using the Service, you consent to the transfer
                and processing of your information in the United States.</p>

            <p>This Privacy Policy describes how Audiobook Librarian ("we," "us," or "our") collects, uses, and
                protects information when you use our application and services.</p>

            <h2 class="h4 mt-5 mb-3">1. Information We Collect</h2>

            <h3 class="h5 mt-4 mb-2">Account Information</h3>
            <p>When you create an account, we collect your email address and a password (stored as a secure hash).
                We do not collect your name unless you choose to provide it.</p>

            <h3 class="h5 mt-4 mb-2">Library and Listening Data</h3>
            <p>To provide the service, we store information about your audiobook library, including:</p>
            <ul>
                <li>Titles, authors, and metadata for books in your library</li>
                <li>Playback position and progress for each book</li>
                <li>Listening history and bookmarks</li>
                <li>Your ratings, notes, and custom shelves</li>
            </ul>
            <p>This data is associated with your account and synchronized across your devices.</p>

            <h3 class="h5 mt-4 mb-2">Device and Technical Information</h3>
            <p>We collect a device identifier to enable multi-device sync and to prevent duplicate event processing.
                This identifier is generated by the app and resets if you reinstall or clear app data. We do not
                collect hardware serial numbers, advertising identifiers, or other persistent device identifiers.</p>

            <h3 class="h5 mt-4 mb-2">Usage Events</h3>
            <p>We record events such as plays, pauses, and position updates as part of the synchronization system.
                These events are used solely to keep your library state consistent across devices and are not used
                for analytics or advertising.</p>

            <h2 class="h4 mt-5 mb-3">2. How We Use Your Information</h2>
            <p>We use the information we collect to:</p>
            <ul>
                <li>Operate and maintain your personal audiobook library</li>
                <li>Synchronize your library and listening progress across your devices</li>
                <li>Authenticate your account and keep it secure</li>
                <li>Respond to support requests</li>
            </ul>
            <p>We do not sell, rent, or share your personal information with third parties for marketing or
                advertising purposes.</p>

            <h2 class="h4 mt-5 mb-3">3. Your Audiobook Library</h2>

            <h3 class="h5 mt-4 mb-2">Personal and Shared Libraries</h3>
            <p>Audiobook Librarian is designed for personal libraries. Your library may contain audiobooks that
                you own, have purchased, or have otherwise obtained the right to use. You may share access to your
                library with associates (such as family members) who have been granted access by the library
                administrator. In all cases, it is your responsibility — and that of your library administrator —
                to ensure that access to any content complies with applicable copyright law and the terms under
                which that content was obtained.</p>

            <h3 class="h5 mt-4 mb-2">LibriVox and Public Domain Content</h3>
            <p>Audiobook Librarian supports libraries that include recordings from
                <a href="https://librivox.org" target="_blank" rel="noopener noreferrer">LibriVox</a> and other
                sources of public domain audiobooks. LibriVox recordings are released into the public domain and
                may be freely used, shared, and distributed. We do not claim any rights over such recordings.</p>

            <h2 class="h4 mt-5 mb-3">4. Data Retention</h2>
            <p>We retain your account data for as long as your account is active. If you delete your account, we
                will delete or anonymize your personal data within 30 days, except where retention is required by
                law.</p>
            <p>Sync event records are retained for a rolling 30-day window to support device synchronization, after
                which they are deleted.</p>

            <h2 class="h4 mt-5 mb-3">5. Security</h2>
            <p>We take reasonable technical and organizational measures to protect your information. Passwords are
                stored using strong one-way hashing. Data is transmitted over encrypted connections (HTTPS/TLS).
                However, no method of transmission or storage is completely secure, and we cannot guarantee
                absolute security.</p>

            <h2 class="h4 mt-5 mb-3">6. Your Rights</h2>
            <p>You have the right to:</p>
            <ul>
                <li>Access the personal data we hold about you</li>
                <li>Correct inaccurate data</li>
                <li>Request deletion of your account and associated data</li>
                <li>Export your library data</li>
            </ul>
            <p>To exercise these rights, contact us at the address below.</p>

            <h2 class="h4 mt-5 mb-3">7. Children's Privacy</h2>
            <p>Audiobook Librarian is not directed at children under the age of 13. We do not knowingly collect
                personal information from children under 13. If you believe a child has provided us with personal
                information, please contact us so we can remove it.</p>

            <h2 class="h4 mt-5 mb-3">8. Changes to This Policy</h2>
            <p>We may update this Privacy Policy from time to time. We will notify registered users of material
                changes by posting a notice in the app or by email. Your continued use of the service after changes
                take effect constitutes acceptance of the updated policy.</p>

            <h2 class="h4 mt-5 mb-3">9. Contact</h2>
            <p>If you have questions or concerns about this Privacy Policy, please contact us at:</p>
            <p><strong>Audiobook Librarian</strong><br>
                <a href="mailto:support@ablibrarian.com">support@ablibrarian.com</a></p>
        </div>
    </div>
</div>
@endsection
