@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-7">
                <div class="card">
                    <div class="card-header">Connect to this server</div>
                    <div class="card-body">
                        <p>
                            This page is generated by this Ablibrarian server instance. It is meant for self-hosted
                            servers, so the encoded API URL is this server's own API endpoint rather than an official
                            Ablibrarian domain.
                        </p>

                        <p>
                            If the app is installed, use one of the open buttons below. If it is not installed yet,
                            install it first and return to this page.
                        </p>

                        <div class="d-grid gap-2 mb-3">
                            <a class="btn btn-primary" href="{{ $playerDeepLink }}">Open Player app</a>
                            <a class="btn btn-outline-primary" href="{{ $libraryDeepLink }}">Open Library app</a>
                            <a class="btn btn-outline-secondary" href="{{ $androidLibraryIntent }}">Open or install on Android</a>
                        </div>

                        <div class="row g-2 mb-3">
                            <div class="col-sm-6">
                                <a class="btn btn-link w-100" href="{{ $androidStoreUrl }}">Android store page</a>
                            </div>
                            <div class="col-sm-6">
                                <a class="btn btn-link w-100 {{ $iosStoreUrl === '#' ? 'disabled' : '' }}" href="{{ $iosStoreUrl }}">iOS store page</a>
                            </div>
                        </div>

                        <dl class="mb-0">
                            <dt>Server API URL</dt>
                            <dd><code class="app-connect-value">{{ $apiUrl }}</code></dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script>
            (function () {
                "use strict";

                try {
                    window.localStorage.setItem('ablibrarian_connect_api_url', @json($apiUrl));
                } catch (error) {
                    console.warn('[app-connect] Unable to store API URL for later redirector use.', error);
                }
            })();
        </script>
    @endpush
@endsection
